version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: novapay_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin      
      POSTGRES_DB: novapay_db       
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: novapay_app
    ports:
      - "3000:3001"
    environment: 
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: admin            
      DB_NAME: novapay_db           
      DB_PORT: 5432
      DB_DIALECT: postgres
    depends_on:
      - db

volumes:
  postgres_data: